### ISSUE TITLE
Export dark-theme-colors.js to create a custom theme based on dark-theme

### ISSUE THREAD

**Issue by menberg** [uber-web/baseui#1775]
## Feature description

Would it be possible to export https://github.com/uber-web/baseui/blob/master/src/themes/dark-theme-colors.js in https://github.com/uber-web/baseui/blob/master/src/themes/index.js so that we can create a custom theme based on Base Web's default dark-theme, like described on https://baseweb.design/theming/custom-themes/? I guess we need access to dark-theme-colors.js for this to work, right? Or is there a better way to modify the default dark-theme?

Thanks!

**Comment by gergelyke** [comment]
hi @menberg - have you checked out this part of the docs ? https://baseweb.design/theming/custom-themes/#creating-a-custom-theme

Essentially, you can do something like this:

```js
import {createTheme, darkThemePrimitives} from 'baseui';
const yourTheme = createTheme(
  {
    ... darkThemePrimitives,
    // add all the properties here you'd like to override from the light theme primitives
    primaryFontFamily: '"Comic Sans MS", cursive, sans-serif',
  },
  {
    // add all the theme overrides here - under the hood it uses deep merge
    animation: {
      timing100: '0.50s',
    },
  },
);
```

**Comment by gergelyke** [comment]
Closing this for now - please reopen if this doesn't work for you!

**Comment by menberg** [comment]
Dear Gergely, thanks for your help. When doing it like in the example above, `yourTheme` contains a lot of `undefined` colors property values:

```{ breakpoints: { small: 320, medium: 600, large: 1280 },
  colors:
   { primary50: undefined,
     primary100: undefined,
     primary200: undefined,
     primary300: undefined,
     primary400: undefined,
     primary: undefined,
     primary500: undefined,
     primary600: undefined,
     primary700: undefined,
     negative50: undefined,
     negative100: undefined,
     negative200: undefined,
     negative300: undefined,
     negative400: undefined,
     negative: undefined,
     negative500: undefined,
     negative600: undefined,
     negative700: undefined,
     warning50: undefined,
     warning100: undefined,
     warning200: undefined,
     warning300: undefined,
     warning400: undefined,
     warning: undefined,
     warning500: undefined,
     warning600: undefined,
     warning700: undefined,
     positive50: undefined,
     positive100: undefined,
     positive200: undefined,
     positive300: undefined,
     positive400: undefined,
     positive: undefined,
     positive500: undefined,
     positive600: undefined,
     positive700: undefined,
     white: undefined,
     mono100: undefined,
     mono200: undefined,
     mono300: undefined,
     mono400: undefined,
     mono500: undefined,
     mono600: undefined,
     mono700: undefined,
     mono800: undefined,
     mono900: undefined,
     mono1000: undefined,
     black: undefined,
     rating200: undefined,
     rating400: undefined,
     colorPrimary: undefined,
     colorSecondary: undefined,
     background: undefined,
     backgroundAlt: undefined,
     backgroundInv: undefined,
     foreground: undefined,
     foregroundAlt: undefined,
     foregroundInv: undefined,
     border: undefined,
     borderAlt: undefined,
     borderFocus: undefined,
     borderError: undefined,
     buttonPrimaryFill: undefined,
     buttonPrimaryText: undefined,
     buttonPrimaryHover: undefined,
     buttonPrimaryActive: undefined,
     buttonSecondaryFill: undefined,
     buttonSecondaryText: undefined,
     buttonSecondaryHover: undefined,
     buttonSecondaryActive: undefined,
     buttonTertiaryFill: undefined,
     buttonTertiaryText: undefined,
     buttonTertiaryHover: undefined,
     buttonTertiaryActive: undefined,
     buttonTertiarySelectedFill: undefined,
     buttonTertiarySelectedText: undefined,
     buttonMinimalFill: 'transparent',
     buttonMinimalText: undefined,
     buttonMinimalHover: undefined,
     buttonMinimalActive: undefined,
     buttonDisabledFill: undefined,
     buttonDisabledText: undefined,
     breadcrumbsText: undefined,
     breadcrumbsSeparatorFill: undefined,
     datepickerBackground: undefined,
     datepickerDayFont: undefined,
     datepickerDayFontDisabled: undefined,
     datepickerDayPseudoSelected: undefined,
     datepickerDayPseudoHighlighted: undefined,
     fileUploaderBackgroundColor: undefined,
     fileUploaderBackgroundColorActive: undefined,
     fileUploaderBorderColorActive: undefined,
     fileUploaderBorderColorDefault: undefined,
     fileUploaderMessageColor: undefined,
     linkText: undefined,
     linkVisited: undefined,
     linkHover: undefined,
     linkActive: undefined,
     shadowFocus: 'rgba(39, 110, 241, 0.32)',
     shadowError: 'rgba(229, 73, 55, 0.32)',
     listHeaderFill: '#FFFFFF',
     listBodyFill: undefined,
     listIconFill: undefined,
     listBorder: undefined,
     progressStepsIconActiveFill: undefined,
     tickFill: '#FFFFFF',
     ...etc
```
This leads to an error when rendering the page:

```
Error: Unsupported style value: undefined
    at validateValueType (/node_modules/styletron-engine-atomic/dist/index.js:433:11)
    at injectStylePrefixed (/node_modules/styletron-engine-atomic/dist/index.js:348:9)
    at StyletronServer.renderStyle (/node_modules/styletron-engine-atomic/dist/index.js:704:12)
    at driver (/node_modules/styletron-standard/dist/index.js:16:20)
    at Object.React.createElement [as children] (/node_modules/styletron-react/dist/index.js:283:32)
    at ReactDOMServerRenderer.render (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3664:55)
    at ReactDOMServerRenderer.read (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToString (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at render (/node_modules/next-server/dist/server/render.js:80:16)
    at Object.renderPage (/node_modules/next-server/dist/server/render.js:261:20)
    at Function.getInitialProps (/.next/server/static/development/pages/_document.js:1158:22)
    at Object.loadGetInitialProps (/node_modules/next-server/dist/lib/utils.js:50:35)
    at Object.renderToHTML (/node_modules/next-server/dist/server/render.js:265:36)
```
I'm using Next.js according to the official example: https://github.com/zeit/next.js/tree/canary/examples/with-styletron

To avoid the undefined values, I wanted to include the dark-theme-colors.js, identically to https://github.com/uber-web/baseui/blob/master/src/themes/dark-theme.js.

Thanks again for your support!

**Comment by menberg** [comment]
> Closing this for now - please reopen if this doesn't work for you!

I'm not allowed to reopen this issue.
